name: Pull Request

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      ACCESS_KEY: ${{ vars.MINIO_ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"
      - name: Setup MinIO server
        run: |
          wget https://dl.min.io/server/minio/release/linux-amd64/archive/minio_20230711212934.0.0_amd64.deb -O minio.deb
          sudo dpkg -i minio.deb
          minio server ~/minio --console-address :9090 &
      - name: Install
        run: |
          pip install -r requirements.txt
          pip install -r requirements.test.txt
      - name: Pytest
        run: python -m pytest -vv -x tests
