name: Pull Request

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"
      - name: Install
        run: |
          pip install -r requirements.txt
          pip install -r requirements.test.txt
      - name: Pytest
        run: python -m pytest -vv -x tests
